FROM python:3.12.2

WORKDIR /app

RUN PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0

COPY ./pyproject.toml ./

COPY ./src ./src
COPY ./.env ./.env
COPY ./main.py ./main.py
COPY ./D2Shared ./D2Shared
COPY ./scripts/populate/extern ./scripts/populate/extern

RUN pip install poetry==1.8.3

RUN poetry run poetry install --without dev

EXPOSE 8000

ENTRYPOINT ["poetry", "run", "uvicorn","--workers", "1", "--host", "0.0.0.0", "main:app" ]