FROM python:3.12.2

RUN PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY ./pyproject.toml ./

COPY ./src ./src
COPY ./.env ./.env
COPY ./main.py ./main.py
COPY ./EzreD2Shared ./EzreD2Shared

RUN pip install poetry==1.8.3

RUN poetry run poetry install --without dev

EXPOSE 8000

ENTRYPOINT ["poetry", "run", "uvicorn", "--host", "0.0.0.0", "main:app" ]