FROM python:3.12.2-slim

WORKDIR /app

RUN PYTHONDONTWRITEBYTECODE=1

COPY ./pyproject.toml ./

COPY ./src ./src
COPY ./.env ./.env
COPY ./main.py ./main.py
COPY ./EzreD2Shared ./EzreD2Shared
COPY ./scripts/populate/create_initial_user.py ./scripts/populate/create_initial_user.py

RUN pip install poetry==1.8.3

RUN poetry run poetry install --without dev

EXPOSE 8000

ENTRYPOINT ["poetry", "run", "uvicorn","--workers", "1", "--host", "0.0.0.0", "main:app" ]