"""empty message

Revision ID: 0929d0ffeb9b
Revises: 0ed6f21da530
Create Date: 2024-07-02 22:00:28.506347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0929d0ffeb9b'
down_revision: Union[str, None] = '0ed6f21da530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('range_wait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.CheckConstraint('"end" > start', name='check_end_greater_than_start'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afk_time_at_start', sa.Time(), nullable=True),
    sa.Column('time_between_sentence', sa.Time(), nullable=True),
    sa.Column('time_fighter', sa.Time(), nullable=True),
    sa.Column('time_harvester', sa.Time(), nullable=True),
    sa.Column('randomizer_duration_activity', sa.Float(), nullable=False),
    sa.Column('range_new_map_id', sa.Integer(), nullable=False),
    sa.Column('range_wait_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['range_new_map_id'], ['range_wait.id'], ),
    sa.ForeignKeyConstraint(['range_wait_id'], ['range_wait.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('range_hour_play_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('config_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_end_time_greater_than_start_time'),
    sa.ForeignKeyConstraint(['config_user_id'], ['config_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('range_hour_play_time')
    op.drop_table('config_user')
    op.drop_table('range_wait')
    # ### end Alembic commands ###
