"""empty message

Revision ID: 0956784d34a0
Revises: 7f4c42e1a014
Create Date: 2024-07-05 16:00:39.097339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0956784d34a0'
down_revision: Union[str, None] = '7f4c42e1a014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('equipment_label_key', type_='unique')
        batch_op.create_unique_constraint('unique label for user', ['label', 'user_id'])

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique stat for equipment', ['stat_id', 'equipment_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_constraint('unique stat for equipment', type_='unique')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('unique label for user', type_='unique')
        batch_op.create_unique_constraint('equipment_label_key', ['label'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
