"""empty message

Revision ID: b6b2523b9b0d
Revises: a27a32adac3e
Create Date: 2024-08-13 10:49:09.256221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b2523b9b0d'
down_revision: Union[str, None] = 'a27a32adac3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_path_info',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'name', name='unique path name by character')
    )
    op.create_table('character_path_map',
    sa.Column('character_path_info_id', sa.String(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_path_info_id'], ['character_path_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('character_path_info_id', 'map_id'),
    sa.UniqueConstraint('character_path_info_id', 'order_index', name='unique order index for same path info')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_path_map')
    op.drop_table('character_path_info')
    # ### end Alembic commands ###
