"""empty message

Revision ID: a44e9e76d13c
Revises: 6d2c1b68ca33
Create Date: 2024-08-10 21:59:03.486986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a44e9e76d13c"
down_revision: Union[str, None] = "6d2c1b68ca33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "left_map_was_checked", sa.Boolean(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "right_map_was_checked",
                sa.Boolean(),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "top_map_was_checked", sa.Boolean(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "bot_map_was_checked", sa.Boolean(), server_default="0", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map", schema=None) as batch_op:
        batch_op.drop_column("bot_map_was_checked")
        batch_op.drop_column("top_map_was_checked")
        batch_op.drop_column("right_map_was_checked")
        batch_op.drop_column("left_map_was_checked")

    # ### end Alembic commands ###
