"""empty message

Revision ID: 118bf54b6d64
Revises: a887293bf479
Create Date: 2024-10-06 09:27:19.142271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '118bf54b6d64'
down_revision: Union[str, None] = 'a887293bf479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('range_hour_play_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('range_hour_play_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('config_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_end_time_greater_than_start_time'),
    sa.ForeignKeyConstraint(['config_user_id'], ['config_user.id'], name='range_hour_play_time_config_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='range_hour_play_time_pkey')
    )
    # ### end Alembic commands ###
