"""empty message

Revision ID: 3bb05417e9d9
Revises: b6b2523b9b0d
Create Date: 2024-08-14 11:54:36.715340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bb05417e9d9'
down_revision: Union[str, None] = 'b6b2523b9b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_user', schema=None) as batch_op:
        batch_op.drop_column('randomizer_duration_activity')
        batch_op.drop_column('afk_time_at_start')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('afk_time_at_start', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('randomizer_duration_activity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
