"""empty message

Revision ID: 3572b2542307
Revises: 0929d0ffeb9b
Create Date: 2024-07-03 19:48:48.401017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3572b2542307'
down_revision: Union[str, None] = '0929d0ffeb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_user', schema=None) as batch_op:
        batch_op.drop_constraint('config_user_range_wait_id_fkey', type_='foreignkey')
        batch_op.drop_column('range_wait_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('range_wait_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('config_user_range_wait_id_fkey', 'range_wait', ['range_wait_id'], ['id'])

    # ### end Alembic commands ###
