"""empty message

Revision ID: 3dfdcf8c467d
Revises: 3ec72b3e4ae3
Create Date: 2024-07-13 15:32:15.726761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfdcf8c467d'
down_revision: Union[str, None] = '3ec72b3e4ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exo_line_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'line', ['exo_line_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exo_line_id')

    # ### end Alembic commands ###
