"""empty message

Revision ID: 3ec72b3e4ae3
Revises: ec6dec1f7ebf
Create Date: 2024-07-13 14:36:34.253422

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ec72b3e4ae3"
down_revision: Union[str, None] = "ec6dec1f7ebf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM equipment")
    op.execute("DELETE FROM line")
    op.execute("DELETE FROM rune")
    op.execute("DELETE FROM stat")
    with op.batch_alter_table("rune", schema=None) as batch_op:
        batch_op.add_column(sa.Column("item_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "item", ["item_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rune", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("item_id")

    # ### end Alembic commands ###
