"""empty message

Revision ID: 491d8aaa6926
Revises: 6d2c1bca2753
Create Date: 2024-08-09 14:03:02.855707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '491d8aaa6926'
down_revision: Union[str, None] = '6d2c1bca2753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_sell_item_info',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('sale_hotel_quantities', postgresql.ARRAY(sa.Enum('ONE', 'TEN', 'HUNDRED', name='salehotelquantity')), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'item_id')
    )
    op.drop_table('character_sell_items_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_sell_items_association',
    sa.Column('character_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_sell_items_association_character_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='character_sell_items_association_item_id_fkey')
    )
    op.drop_table('character_sell_item_info')
    # ### end Alembic commands ###
