"""empty message

Revision ID: 66b8576bcba9
Revises: f187bd667697
Create Date: 2024-07-10 18:18:45.243672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b8576bcba9'
down_revision: Union[str, None] = 'f187bd667697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_sub_areas_association',
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('sub_area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_area_id'], ['sub_area.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_sub_areas_association')
    # ### end Alembic commands ###
