"""empty message

Revision ID: 7f4c42e1a014
Revises: 3572b2542307
Create Date: 2024-07-05 11:51:17.451409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4c42e1a014'
down_revision: Union[str, None] = '3572b2542307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rune', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_quantity', sa.Integer(), nullable=False))
        batch_op.drop_constraint('unique name with quantity', type_='unique')
        batch_op.create_unique_constraint('unique name with quantity', ['name', 'stat_quantity'])
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rune', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('unique name with quantity', type_='unique')
        batch_op.create_unique_constraint('unique name with quantity', ['name', 'quantity'])
        batch_op.drop_column('stat_quantity')

    # ### end Alembic commands ###
