"""empty message

Revision ID: 84cef97cd767
Revises: d438ae892c41
Create Date: 2024-07-23 19:45:42.203432

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84cef97cd767"
down_revision: Union[str, None] = "d438ae892c41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "count_lines_achieved", sa.Integer(), nullable=False, server_default="0"
            )
        )
        batch_op.drop_column("exo_attempt")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "exo_attempt",
                sa.INTEGER(),
                server_default=sa.text("0"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("count_lines_achieved")

    # ### end Alembic commands ###
