"""empty message

Revision ID: b11459a36c90
Revises: 0956784d34a0
Create Date: 2024-07-06 15:10:41.369454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11459a36c90'
down_revision: Union[str, None] = '0956784d34a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_constraint('line_equipment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('line_equipment_id_fkey', 'equipment', ['equipment_id'], ['id'])

    # ### end Alembic commands ###
