"""empty message

Revision ID: c7cfdbd5e4ff
Revises: 
Create Date: 2024-06-19 11:51:49.173353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7cfdbd5e4ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('breed',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characteristic_category',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('icon',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monster',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('earth_resistance', sa.Integer(), nullable=False),
    sa.Column('air_resistance', sa.Integer(), nullable=False),
    sa.Column('fire_resistance', sa.Integer(), nullable=False),
    sa.Column('water_resistance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left', sa.Integer(), nullable=False),
    sa.Column('right', sa.Integer(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=False),
    sa.Column('bot', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left', 'right', 'top', 'bot', name='unique region')
    )
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.CheckConstraint('weight>=0', name='check positive weight'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template_found',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('type_item',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('ALL', 'EQUIPMENT', 'CONSUMABLES', 'RESOURCES', 'QUEST', 'OTHER', 'COSMETICS', 'ECAFLIP_CARD', name='categoryenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('world',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('character',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('po_bonus', sa.Integer(), nullable=False),
    sa.Column('is_sub', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Float(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('elem', sa.Enum('ELEMENT_NEUTRAL', 'ELEMENT_EARTH', 'ELEMENT_FIRE', 'ELEMENT_WATER', 'ELEMENT_AIR', name='elemenum'), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('lvl>=1 AND lvl<=200', name='check legit character lvl'),
    sa.CheckConstraint('po_bonus>=0', name='check positive po bonus'),
    sa.CheckConstraint('time_spent>=0', name='check positive time_spent'),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('characteristic_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characteristic_category_id'], ['characteristic_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_item_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('is_saleable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['icon_id'], ['icon.id'], ),
    sa.ForeignKeyConstraint(['type_item_id'], ['type_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rune',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity>=0', name='check positive quantity'),
    sa.ForeignKeyConstraint(['stat_id'], ['stat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'quantity', name='unique name with quantity')
    )
    op.create_table('spell_variant',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_area',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'area_id', name='unique sub area in area')
    )
    op.create_table('character_items_association',
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], )
    )
    op.create_table('character_job_info',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.CheckConstraint('lvl>=1 AND lvl<=200', name='check legit character job lvl'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'job_id')
    )
    op.create_table('collectable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('drop',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monster_id', 'item_id', name='unique drop')
    )
    op.create_table('effect',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_boost', sa.Boolean(), nullable=False),
    sa.Column('characteristic_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('elem', sa.Enum('ELEMENT_NEUTRAL', 'ELEMENT_EARTH', 'ELEMENT_FIRE', 'ELEMENT_WATER', 'ELEMENT_AIR', name='elemenum'), nullable=True),
    sa.Column('use_in_fight', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('sub_area_id', sa.Integer(), nullable=False),
    sa.Column('allow_teleport_from', sa.Boolean(), nullable=False),
    sa.Column('allow_monster_fight', sa.Boolean(), nullable=False),
    sa.Column('has_priority_on_world_map', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sub_area_id'], ['sub_area.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster_sub_area_association',
    sa.Column('sub_area_id', sa.Integer(), nullable=True),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], ),
    sa.ForeignKeyConstraint(['sub_area_id'], ['sub_area.id'], )
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.CheckConstraint('average>=0', name='check positive price'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'server_id', name='unique price by server item')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_item_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['result_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_item_id')
    )
    op.create_table('spell',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spell_variant_id', sa.Integer(), nullable=False),
    sa.Column('default_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_variant_id'], ['spell_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collectable_map_info',
    sa.Column('collectable_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collectable_id'], ['collectable.id'], ),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('collectable_id', 'map_id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'recipe_id', name='unique ingredient on recipe')
    )
    op.create_table('map_direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_map_id', sa.Integer(), nullable=False),
    sa.Column('from_direction', sa.Enum('TOP_LEFT', 'TOP', 'TOP_RIGHT', 'BOT_LEFT', 'BOT', 'BOT_RIGHT', 'RIGHT_TOP', 'RIGHT', 'RIGHT_BOT', 'LEFT_TOP', 'LEFT', 'LEFT_BOT', 'WAYPOINT', 'ZAAPI', 'UNKNOWN', name='fromdirection'), nullable=False),
    sa.Column('to_map_id', sa.Integer(), nullable=False),
    sa.Column('to_direction', sa.Enum('TOP_LEFT', 'TOP', 'TOP_RIGHT', 'BOT_LEFT', 'BOT', 'BOT_RIGHT', 'RIGHT_TOP', 'RIGHT', 'RIGHT_BOT', 'LEFT_TOP', 'LEFT', 'LEFT_BOT', name='todirection'), nullable=False),
    sa.Column('was_checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_map_id'], ['map.id'], ),
    sa.ForeignKeyConstraint(['to_map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_map_id', 'from_direction', 'to_map_id', 'to_direction', name='unique direction')
    )
    op.create_table('spell_level',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('ap_cost', sa.Integer(), nullable=False),
    sa.Column('max_cast', sa.Integer(), nullable=False),
    sa.Column('min_range', sa.Integer(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('can_cast_in_line', sa.Boolean(), nullable=False),
    sa.Column('can_cast_in_diagonal', sa.Boolean(), nullable=False),
    sa.Column('need_los', sa.Boolean(), nullable=False),
    sa.Column('is_disenchantment', sa.Boolean(), nullable=False),
    sa.Column('is_boost', sa.Boolean(), nullable=False),
    sa.Column('is_healing', sa.Boolean(), nullable=False),
    sa.Column('on_enemy', sa.Boolean(), nullable=False),
    sa.Column('duration_boost', sa.Integer(), nullable=False),
    sa.Column('need_free_cell', sa.Boolean(), nullable=False),
    sa.Column('need_taken_cell', sa.Boolean(), nullable=False),
    sa.Column('need_visible_entity', sa.Boolean(), nullable=False),
    sa.Column('range_can_be_boosted', sa.Boolean(), nullable=False),
    sa.Column('max_stack', sa.Integer(), nullable=False),
    sa.Column('min_cast_interval', sa.Integer(), nullable=False),
    sa.Column('initial_cooldown', sa.Integer(), nullable=False),
    sa.Column('global_cooldown', sa.Integer(), nullable=False),
    sa.Column('min_player_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_found_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('template_found_id', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.ForeignKeyConstraint(['template_found_id'], ['template_found.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id', 'template_found_id', name='unique template map found')
    )
    op.create_table('waypoint',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id')
    )
    op.create_table('character_waypoint_association',
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('waypoint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoint.id'], )
    )
    op.create_table('spell_level_effect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spell_level_id', sa.Integer(), nullable=False),
    sa.Column('effect_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('dispellable', sa.Enum('IS_DISPELLABLE', 'IS_DISPELLABLE_ONLY_BY_DEATH', 'IS_NOT_DISPELLABLE', name='dispellableenum'), nullable=False),
    sa.ForeignKeyConstraint(['effect_id'], ['effect.id'], ),
    sa.ForeignKeyConstraint(['spell_level_id'], ['spell_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_found_placement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_found_map_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['template_found_map_id'], ['template_found_map.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_found_map_id', 'region_id', name='unique template found place')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_found_placement')
    op.drop_table('spell_level_effect')
    op.drop_table('character_waypoint_association')
    op.drop_table('waypoint')
    op.drop_table('template_found_map')
    op.drop_table('spell_level')
    op.drop_table('map_direction')
    op.drop_table('ingredient')
    op.drop_table('collectable_map_info')
    op.drop_table('spell')
    op.drop_table('recipe')
    op.drop_table('price')
    op.drop_table('monster_sub_area_association')
    op.drop_table('map')
    op.drop_table('effect')
    op.drop_table('drop')
    op.drop_table('collectable')
    op.drop_table('character_job_info')
    op.drop_table('character_items_association')
    op.drop_table('sub_area')
    op.drop_table('spell_variant')
    op.drop_table('rune')
    op.drop_table('line')
    op.drop_table('item')
    op.drop_table('characteristic')
    op.drop_table('character')
    op.drop_table('world')
    op.drop_table('type_item')
    op.drop_table('template_found')
    op.drop_table('stat')
    op.drop_table('server')
    op.drop_table('region')
    op.drop_table('monster')
    op.drop_table('job')
    op.drop_table('icon')
    op.drop_table('equipment')
    op.drop_table('characteristic_category')
    op.drop_table('breed')
    op.drop_table('area')
    # ### end Alembic commands ###
